<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-35MR1O66" failures="2" tests="4" name="APIAutomationFramework" time="2.713" errors="0" timestamp="2023-09-20T12:18:18 EDT">
  <testcase classname="api.test.UserTest2" name="testDeleteUser" time="1.245">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTest2.testDeleteUser(UserTest2.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.UserTest2" name="testUpdateUserByName" time="0.614"/>
  <testcase classname="api.test.UserTest2" name="testPostReq" time="0.103"/>
  <testcase classname="api.test.UserTest2" name="testGetReq" time="0.068">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTest2.testGetReq(UserTest2.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGetReq -->
</testsuite> <!-- APIAutomationFramework -->
